[serviceweaver]
binary = "./emojis-demo.exe"

["emojis/ChatGPT"]
api_key = "YOUR SECRET KEY GOES HERE"

[single]
listeners.emojis = {address = "localhost:9000"}

[multi]
listeners.emojis = {address = "localhost:9000"}